language: python

matrix:
  - name: "Python: 3.8"
      os: osx
      language: shell
      python: 3.8
      cache:
        - directories:
          - $HOME/Library/Caches/pip
  
before_install:
  - pip install -U pip
  
cache: pip

install:
  - pip install -r requirements.txt
  
script:
  - pytest
